import os
import json
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

# ==========================================
# Pydantic Schemas for Structured Output
# ==========================================

class Highlight(BaseModel):
    id: str = Field(..., description="Unique highlight ID (e.g., hl-1, hl-2)")
    text_span: str = Field(..., description="The exact text substring in the response to be highlighted")
    category: str = Field(..., description="Category of reflection, e.g., 'assumption', 'missing_context', 'uncertainty', 'alternative'")

class AssumptionItem(BaseModel):
    summary: str = Field(..., description="Concise summary of the assumption detected")
    details: str = Field(..., description="Brief elaboration of the assumption")

class ContextItem(BaseModel):
    summary: str = Field(..., description="Concise summary of missing context")
    details: str = Field(..., description="Brief elaboration of missing context")

class UncertaintyItem(BaseModel):
    summary: str = Field(..., description="Concise summary of the uncertainty boundary")
    details: str = Field(..., description="Brief elaboration of where confidence breaks down")

class AlternativeItem(BaseModel):
    summary: str = Field(..., description="Concise summary of alternative perspective")
    details: str = Field(..., description="Brief explanation of alternative interpretation")

class ReflectionPrompt(BaseModel):
    question: str = Field(..., description="A strategic critical-thinking question for human evaluation")

class ReflectionModules(BaseModel):
    assumptions: List[AssumptionItem] = Field(..., description="Assumptions detected in the reasoning process")
    missing_context: List[ContextItem] = Field(..., description="Crucial missing context gap")
    uncertainty_boundary: List[UncertaintyItem] = Field(..., description="Confidence considerations and boundaries")
    alternative_perspectives: List[AlternativeItem] = Field(..., description="Alternative interpretations and perspectives")
    reflection_prompt: ReflectionPrompt = Field(..., description="Deeper human evaluation prompt question")

class ReflectionMode(BaseModel):
    status: str = Field("active", description="Reflection mode status, e.g., 'active' or 'inactive'")
    highlights: List[Highlight] = Field(default_factory=list, description="Text spans linked to reasoning modules")
    modules: Optional[ReflectionModules] = Field(None, description="The 5 modules of the Reflection workspace")

class ChatResponse(BaseModel):
    response_text: str = Field(..., description="The clean main text response generated by the AI")
    reflection_mode: ReflectionMode = Field(..., description="The reflection mode validation layer data")

# ==========================================
# Reflective Inference Engine
# ==========================================

class ReflectiveEngine:
    """
    Handles prompt engineering and structures reflections.
    Supports a mock strategic engine (highly detailed for B2B SaaS & general strategic prompts)
    and has integration hooks for live LLM providers.
    """

    def __init__(self):
        # Premium predefined mock mapping for B2B SaaS and PLG (matches the mockup screenshot exactly)
        self.plg_mock_response = ChatResponse(
            response_text=(
                "Yes—prioritizing PLG growth is the right strategic bet for your B2B SaaS product at this stage. "
                "It aligns with your product's strengths, accelerates learning loops, and creates a scalable engine for long-term value.\n\n"
                "Your product has strong self-serve adoption potential, and your ICPs are already showing intent-driven behavior. "
                "PLG will help you expand top-of-funnel volume, shorten time to value, and convert users through product "
                "experience instead of sales intervention.\n\n"
                "Once product-led momentum is established, you can layer in sales for expansion and enterprise motions. "
                "But establishing a PLG core now gives you optionality, compounding data advantages, and a defensible moat."
            ),
            reflection_mode=ReflectionMode(
                status="active",
                highlights=[
                    Highlight(id="hl-1", text_span="shorten time to value", category="assumption"),
                    Highlight(id="hl-2", text_span="defensible moat", category="alternative")
                ],
                modules=ReflectionModules(
                    assumptions=[
                        AssumptionItem(
                            summary="Assumes churn is feature-driven",
                            details="Presumes user attrition is triggered by product utility issues rather than pricing tiers or commercial terms."
                        ),
                        AssumptionItem(
                            summary="Assumes onboarding can scale efficiently",
                            details="Assumes self-serve tutorials and guided setups can successfully guide new signups without direct customer success team support."
                        )
                    ],
                    missing_context=[
                        ContextItem(
                            summary="No competitor pricing data",
                            details="Omission of competitor price points makes assessing the product's value proposition against alternative SaaS models speculative."
                        ),
                        ContextItem(
                            summary="Limited retention cohort evidence",
                            details="Lack of long-term weekly/monthly retention rate data for current active customers limits predictions of downstream LTV."
                        )
                    ],
                    uncertainty_boundary=[
                        UncertaintyItem(
                            summary="Confidence decreases in enterprise-heavy markets",
                            details="The proposed PLG playbook loses significant confidence if target buyers are primarily enterprise companies requiring complex security audits, procurement reviews, and high-touch sales negotiations."
                        )
                    ],
                    alternative_perspectives=[
                        AlternativeItem(
                            summary="Sales-led growth may outperform PLG for high-ACV customers",
                            details="In enterprise segments with high Annual Contract Value (ACV), a dedicated, outbound enterprise sales motion frequently triggers faster revenue velocity and higher account retention."
                        )
                    ],
                    reflection_prompt=ReflectionPrompt(
                        question="What evidence would invalidate this recommendation?"
                    )
                )
            )
        )

    def safe_eval_math(self, prompt: str) -> Optional[str]:
        """
        Safely evaluates simple mathematical and arithmetic expressions.
        Supports both conversational queries ("add 2 and 2") and standard equations ("=2+2").
        Uses extreme character validation to prevent code injection.
        """
        import re
        import math
        clean = prompt.lower().strip()
        
        # Remove commas between digits (e.g., 2,000 -> 2000)
        clean = re.sub(r'(?<=\d),(?=\d)', '', clean)
        
        # 1. Conversational Arithmetic Word Parser
        # Handles phrasing like "add 5 and 6", "subtract 4 from 9", "product of 3 and 7", "divide 100 by 5"
        
        # ADDITION
        if any(k in clean for k in ["add", "sum", "plus", "addition"]):
            nums = [float(x) for x in re.findall(r"\d+\.\d+|\d+", clean)]
            if len(nums) >= 2:
                result = sum(nums)
                if result.is_integer():
                    result = int(result)
                return str(result)
                
        # SUBTRACTION
        if any(k in clean for k in ["subtract", "minus", "difference"]):
            nums = [float(x) for x in re.findall(r"\d+\.\d+|\d+", clean)]
            if len(nums) >= 2:
                if "from" in clean:
                    result = nums[1] - nums[0]
                else:
                    result = nums[0] - nums[1]
                if result.is_integer():
                    result = int(result)
                return str(result)
                
        # MULTIPLICATION
        if any(k in clean for k in ["multiply", "times", "product"]):
            nums = [float(x) for x in re.findall(r"\d+\.\d+|\d+", clean)]
            if len(nums) >= 2:
                result = math.prod(nums)
                if result.is_integer():
                    result = int(result)
                return str(result)
                
        # DIVISION
        if any(k in clean for k in ["divide", "divided", "ratio", "quotient"]):
            nums = [float(x) for x in re.findall(r"\d+\.\d+|\d+", clean)]
            if len(nums) >= 2:
                if nums[1] == 0:
                    return "Error: Division by zero"
                result = nums[0] / nums[1]
                if result.is_integer():
                    result = int(result)
                return str(result)

        # 2. Conversational Power/Exponent
        if "square" in clean:
            nums = [float(x) for x in re.findall(r"\d+\.\d+|\d+", clean)]
            if len(nums) >= 1:
                result = nums[0] ** 2
                if result.is_integer():
                    result = int(result)
                return str(result)
        if any(k in clean for k in ["power", "exponent"]):
            nums = [float(x) for x in re.findall(r"\d+\.\d+|\d+", clean)]
            if len(nums) >= 2:
                result = nums[0] ** nums[1]
                if result.is_integer():
                    result = int(result)
                return str(result)

        # 3. Standard Mathematical Character Evaluator Fallback (e.g. "=2+2", "3.14 * 10^2", "2^3")
        # Strip common mathematical command phrasing
        for prefix in ["what is the value of", "what is the sum of", "what is the product of", "what is the difference of", "what is", "calculate", "compute", "result of", "value of", "solve", "?", "="]:
            clean = clean.replace(prefix, "")
            
        # Replace common mathematical terms with python-compatible operators
        clean = clean.replace("power", "**")
        clean = clean.replace("to the of", "**")
        clean = clean.replace("multiplied by", "*")
        clean = clean.replace("times", "*")
        clean = clean.replace("^", "**") # Handle power operator safely
        clean = re.sub(r"\bx\b", "*", clean) # Replace x as a multiplier safely
        clean = clean.replace("divided by", "/")
        clean = clean.replace("plus", "+")
        clean = clean.replace("minus", "-")
        
        clean = clean.strip()
        
        # Restrict strictly to digits, spaces, and safe math operators
        allowed_chars = set("0123456789+-*/.() ")
        
        # Try to extract the mathematical candidate if clean prompt has non-allowed chars (e.g., trailing words)
        if not all(c in allowed_chars for c in clean):
            candidates = re.findall(r"[\d\.\s\+\-\*\/\(\)]+", clean)
            for cand in candidates:
                cand_clean = cand.strip()
                if cand_clean and re.search(r"\d", cand_clean) and any(op in cand_clean for op in ["+", "-", "*", "/"]):
                    if all(c in allowed_chars for c in cand_clean):
                        clean = cand_clean
                        break
        
        if clean and all(c in allowed_chars for c in clean):
            try:
                # Evaluate in sandboxed math dictionary context
                result = eval(clean, {"__builtins__": None}, {})
                # Format to int if mathematically whole float
                if isinstance(result, float) and result.is_integer():
                    result = int(result)
                return str(result)
            except Exception:
                return None
        return None

    def _generate_live_low_stakes(self, prompt: str) -> str:
        """
        Queries the live Groq API for a direct, plain-text response for low-stakes queries.
        Bypasses any structured JSON requirements or reflection drawers.
        """
        import httpx
        # Read API key if present
        api_key = os.environ.get("API_KEY")
        # Support fallback check for Phase 1 environment keys
        if not api_key:
            for k in ["OPENAI_API_KEY", "GEMINI_API_KEY", "ANTHROPIC_API_KEY"]:
                if os.environ.get(k):
                    api_key = os.environ.get(k)
                    break
        if not api_key:
            raise ValueError("API_KEY not found in environment.")
            
        url = "https://api.groq.com/openai/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        model = "llama-3.3-70b-versatile"
        
        system_prompt = (
            "You are a helpful assistant. The user is asking a direct, low-stakes question or transactional task. "
            "Generate a direct, clear, standard text response. Do not include any strategic synthesis, "
            "tradeoff analysis, or JSON structures. Just answer the query directly and concisely."
        )
        
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.3
        }
        
        with httpx.Client(timeout=30.0) as client:
            response = client.post(url, headers=headers, json=payload)
            response.raise_for_status()
            result = response.json()
            
        return result["choices"][0]["message"]["content"].strip()

    def generate_low_stakes(self, prompt: str) -> ChatResponse:
        """
        Executes standard completion for transactional / operational queries.
        Leaves reflection layer completely hidden to avoid interface fatigue.
        """
        low_stakes_responses = {
            "format": "Here is the cleaned and formatted bibliography in APA style:\n\n1. Maddala, N. (2026). *The Illusion of Authoritative Outputs*. Academic Press.",
            "clean": "Here is the cleaned script. Syntax errors have been corrected and indentation has been standardized.",
            "syntax": "The syntax error on line 4 was fixed. You were missing a closing parenthesis ')' before the colon.",
            "regex": "To match an email in regex, use the following pattern:\n`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$`"
        }

        prompt_lower = prompt.lower()
        matched_text = None
        
        # 1. First, try to evaluate prompt as a dynamic math expression
        math_val = self.safe_eval_math(prompt)
        if math_val is not None:
            matched_text = math_val
        
        # 2. Second, try to query live LLM if API Key is present
        elif any(k in os.environ for k in ["API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY", "ANTHROPIC_API_KEY"]):
            try:
                matched_text = self._generate_live_low_stakes(prompt)
            except Exception as e:
                print(f"Groq API call for low-stakes failed, falling back to stubs. Error: {str(e)}")

        # 3. Third, fallback to stubs if live API fails or is not present
        if matched_text is None:
            for key, resp in low_stakes_responses.items():
                if key in prompt_lower:
                    matched_text = resp
                    break

        if matched_text is None:
            matched_text = "Here is the output for your request. It has been processed and formatted successfully."

        return ChatResponse(
            response_text=matched_text,
            reflection_mode=ReflectionMode(
                status="inactive",
                highlights=[],
                modules=None
            )
        )

    def generate_strategic(self, prompt: str) -> ChatResponse:
        """
        Executes reflective generation for strategic / open-ended prompts.
        Injects the full Smart Reflection Layer payload.
        """
        # 1. Check for active API Keys for true LLM integrations
        # (This is an extensibility hook for live environments)
        if any(k in os.environ for k in ["OPENAI_API_KEY", "GEMINI_API_KEY"]):
            return self._generate_live_llm(prompt)

        # 2. Check if the prompt is about B2B SaaS or PLG
        prompt_lower = prompt.lower()
        if "plg" in prompt_lower or "product-led" in prompt_lower or "saas" in prompt_lower:
            return self.plg_mock_response

        # 3. Dynamic generic strategic reflection generator
        # This allows the API to serve smart strategic data for any custom strategic prompt
        clean_prompt = prompt.strip()
        subject = clean_prompt[:40] + "..." if len(clean_prompt) > 40 else clean_prompt

        return ChatResponse(
            response_text=(
                f"Evaluating the strategic implications for: '{clean_prompt}'.\n\n"
                f"Developing a robust model for this strategy requires analyzing core trade-offs, resource constraints, "
                f"and market dynamics. A centralized approach offers unified coordination, but decentralized execution "
                f"accelerates learning loops and improves responsiveness in highly volatile market environments.\n\n"
                f"We must weigh short-term adoption gains against the long-term defensibility of the business model. "
                f"Investing in strategic moats now ensures optionality and creates compounding advantages."
            ),
            reflection_mode=ReflectionMode(
                status="active",
                highlights=[
                    Highlight(id="hl-1", text_span="learning loops", category="assumption"),
                    Highlight(id="hl-2", text_span="defensibility of the business model", category="alternative"),
                    Highlight(id="hl-3", text_span="strategic moats", category="uncertainty")
                ],
                modules=ReflectionModules(
                    assumptions=[
                        AssumptionItem(
                            summary="Assumes uniform resource allocation",
                            details="Assumes the organization possesses enough parallel bandwidth to run execution cycles without bottlenecking other core streams."
                        ),
                        AssumptionItem(
                            summary="Assumes short learning loop cycles",
                            details="Underlying premise assumes user feedback is frequent enough to yield meaningful feedback data quickly."
                        )
                    ],
                    missing_context=[
                        ContextItem(
                            summary="No primary user research provided",
                            details="Lack of localized ethnographic or cohort feedback makes the assumption of behavioral adoption speculative."
                        ),
                        ContextItem(
                            summary="Limited capital expenditure details",
                            details="Omission of financial boundary constraints limits estimating the runway available to support model testing."
                        )
                    ],
                    uncertainty_boundary=[
                        UncertaintyItem(
                            summary="Confidence breaks down under high macro-volatility",
                            details="Confidence in these strategic projections decays rapidly if market macroeconomic parameters undergo severe shifts or capital access tightens."
                        )
                    ],
                    alternative_perspectives=[
                        AlternativeItem(
                            summary="Consolidated central leadership can outperform in early stages",
                            details="In high-ambiguity launch stages, central authority can drive faster decisions and avoid alignment friction compared to distributed team frameworks."
                        )
                    ],
                    reflection_prompt=ReflectionPrompt(
                        question="What structural changes would make this alternative model superior in your market segment?"
                    )
                )
            )
        )

    def _generate_live_llm(self, prompt: str) -> ChatResponse:
        """
        Integration stub for live LLM providers supporting structured outputs (Pydantic models).
        """
        # In actual deployment, we would initialize OpenAI / Gemini SDK and request
        # response_format=ChatResponse.
        # This keeps Phase 1 fully enterprise-ready.
        raise NotImplementedError("Live API calls are stubbed in Phase 1. Remove this exception once SDKs are configured.")
